src/Entity/Segments.php
<?php

namespace App\Entity;

use App\Repository\SegmentsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=SegmentsRepository::class)
 */
class Segments
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(max=2)
     */
    private $part;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $title1;

    /**
     * @ORM\Column(type="text")
     */
    private $message1;

    /**
     * @ORM\Column(type="text")
     */
    private $link1;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title2;

    /**
     * @ORM\Column(type="text")
     */
    private $message2;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $link2;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $link_s1;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $link_s2;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $link_s3;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link3;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPart(): ?string
    {
        return $this->part;
    }

    public function setPart(string $part): self
    {
        $this->part = $part;

        return $this;
    }

    public function getTitle1(): ?string
    {
        return $this->title1;
    }

    public function setTitle1(string $title1): self
    {
        $this->title1 = $title1;

        return $this;
    }

    public function getMessage1(): ?string
    {
        return $this->message1;
    }

    public function setMessage1(string $message1): self
    {
        $this->message1 = $message1;

        return $this;
    }

    public function getLink1(): ?string
    {
        return $this->link1;
    }

    public function setLink1(string $link1): self
    {
        $this->link1 = $link1;

        return $this;
    }

    public function getTitle2(): ?string
    {
        return $this->title2;
    }

    public function setTitle2(string $title2): self
    {
        $this->title2 = $title2;

        return $this;
    }

    public function getMessage2(): ?string
    {
        return $this->message2;
    }

    public function setMessage2(string $message2): self
    {
        $this->message2 = $message2;

        return $this;
    }

    public function getLink2(): ?string
    {
        return $this->link2;
    }

    public function setLink2(?string $link2): self
    {
        $this->link2 = $link2;

        return $this;
    }

    public function getLinkS1(): ?string
    {
        return $this->link_s1;
    }

    public function setLinkS1(?string $link_s1): self
    {
        $this->link_s1 = $link_s1;

        return $this;
    }

    public function getLinkS2(): ?string
    {
        return $this->link_s2;
    }

    public function setLinkS2(?string $link_s2): self
    {
        $this->link_s2 = $link_s2;

        return $this;
    }

    public function getLinkS3(): ?string
    {
        return $this->link_s3;
    }

    public function setLinkS3(?string $link_s3): self
    {
        $this->link_s3 = $link_s3;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getLink3(): ?string
    {
        return $this->link3;
    }

    public function setLink3(?string $link3): self
    {
        $this->link3 = $link3;

        return $this;
    }
}

src/Entity/Splash.php
<?php

namespace App\Entity;

use App\Repository\SplashRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SplashRepository::class)
 */
class Splash
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Message;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Link;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_At;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(string $Message): self
    {
        $this->Message = $Message;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->Link;
    }

    public function setLink(string $Link): self
    {
        $this->Link = $Link;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_At;
    }

    public function setCreatedAt(\DateTimeInterface $created_At): self
    {
        $this->created_At = $created_At;

        return $this;
    }
}

src/Controller/BackController.php
<?php

namespace App\Controller;

use App\Entity\Splash;
use App\Entity\Segments;

use App\Form\SplashType;

use App\Form\SegmentType;
use App\Repository\SplashRepository;
use App\Repository\SegmentsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BackController extends AbstractController
{


    /**
     * @Route("/splashPage/{id}", name="splashPage")
     */
    public function splashPage(Splash $splash = null, SplashRepository $repo,  Request $request, EntityManagerInterface $manager)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
 

        if(!$splash) 
        {
            $splash = new Splash(); 
        }

        $update = $repo->findAll();

        $form = $this->createForm(SplashType::class, $splash);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) 
        {
            $splash->setCreatedAt(new \DateTime());
            $manager->persist($splash);
            $manager->flush();

            $this->addFlash(
                'success',
                'Your splash page has been updated and it look AWESOME !'
            );

            return $this->render('back/splashPage.html.twig', [
                'controller_name' => 'BackController',
                'form' => $form->createView(),
                'update' => $update
            ]);
        }

        return $this->render('back/splashPage.html.twig', [
            'controller_name' => 'BackController',
            'form' => $form->createView(),
            'update' => $update
        ]);
    }

    /**
     * @Route("/segmentView", name="segmentView")
     */
    public function segmentView(SegmentsRepository $repo)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $segments = $repo->findBy(['deleted'=>false]);

        $trash = $repo->findBy(['deleted'=>true]);

        return $this->render('back/segmentView.html.twig', [
            'controller_name' => 'BackController',
            'segments' => $segments,
            'trash' => $trash
        ]);
    }
        
    /**
     * @Route("/segmentAdd", name="segmentAdd")
     * @Route("/segmentEdit/{id}", name="segmentEdit")
     */
    public function segmentForm(Segments $segments = null, SegmentsRepository $repo, Request $request, EntityManagerInterface $manager, SluggerInterface $slugger)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        if(!$segments) {
            $segments = new Segments(); 
            $updates = null;
        } else {
            $updates = $repo->find($segments);
        }

        $form = $this->createForm(SegmentType::class, $segments);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) 
        {
            /** @var UploadedFile $link1 */
            $link1 = $form->get('link_s1')->getData();
            $link2 = $form->get('link_s2')->getData();
            $link3 = $form->get('link_s3')->getData();
            

            if ($link1) {
                $originalFilename = pathinfo($link1->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$link1->guessExtension();

                try {
                    $link1->move(
                        $this->getParameter('links_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $segments->setlinkS1($newFilename);
            }

            if ($link2) {
                $originalFilename = pathinfo($link2->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$link2->guessExtension();

                try {
                    $link2->move(
                        $this->getParameter('links_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $segments->setlinkS2($newFilename);
            }

            if ($link3) {
                $originalFilename = pathinfo($link3->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$link3->guessExtension();

                try {
                    $link3->move(
                        $this->getParameter('links_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $segments->setlinkS3($newFilename);
            }

            $segments->setCreatedAt(new \DateTime());
            $segments->setDeleted(false);
            $manager->persist($segments);
            $manager->flush();

            if($updates) {
                $this->addFlash(
                    'success',
                    'Your segment have been updeated.'
                );
                return $this->redirect($request->getUri());
            } else {
                $this->addFlash(
                    'success',
                    'Your segment have been published.'
                );
                return $this->redirectToRoute('segmentView');
            }
        }
        
        return $this->render('back/segmentForm.html.twig', [
            'formSegment' => $form->createView(),
            'editMode' => $segments->getId() !==null,
            'updates' => $updates
        ]);
    }

    /**
     * @Route("/segmentImgT1/{id}", name="segmentImgTrash1")
     */
    public function segmentImgTrash(Segments $segments, EntityManagerInterface $manager, Request $request)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $name = $segments->getlinkS1(); 
        unlink($this->getParameter('links_directory'). '/'.$name);

        $segments->setLinkS1(null);
        $manager->persist($segments);
        $manager->flush();

        return $this->redirectToRoute('segmentEdit', [
            'id' => $segments->getId()
        ]);
    }

        /**
     * @Route("/segmentImgT2/{id}", name="segmentImgTrash2")
     */
    public function segmentImgTrash2(Segments $segments, EntityManagerInterface $manager, Request $request)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $name = $segments->getlinkS2(); 
        unlink($this->getParameter('links_directory'). '/'.$name);

        $segments->setLinkS2(null);
        $manager->persist($segments);
        $manager->flush();

        return $this->redirectToRoute('segmentEdit', [
            'id' => $segments->getId()
        ]);
    }

        /**
     * @Route("/segmentImgT3/{id}", name="segmentImgTrash3")
     */
    public function segmentImgTrash3(Segments $segments, EntityManagerInterface $manager, Request $request)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $name = $segments->getlinkS3(); 
        unlink($this->getParameter('links_directory'). '/'.$name);

        $segments->setLinkS3(null);
        $manager->persist($segments);
        $manager->flush();

        return $this->redirectToRoute('segmentEdit', [
            'id' => $segments->getId()
        ]);
    }

     /**
     * @Route("/segmentBin/{id}", name="segmentBin")
     */
    public function segmentBin($id)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $entityManager = $this->getDoctrine()->getManager();
        $delete = $entityManager->getRepository(segments::class)->find($id);

        $delete->setDeleted(true);
        $entityManager->flush();

        $this->addFlash(
            'warning',
            'Your segment have been placed in the trash.'
        );

        return $this->redirectToRoute('segmentView');
    }

    /**
     * @Route("/segmentRft/{id}", name="removeFromTrash")
     */
    public function removeFromTrash($id)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $entityManager = $this->getDoctrine()->getManager();
        $remove = $entityManager->getRepository(segments::class)->find($id);

        $remove->setDeleted(false);
        $entityManager->flush();

        $this->addFlash(
            'success',
            'Your segment have removed from the trash.'
        );

        return $this->redirectToRoute('segmentTrash');
    }

    /**
     * @Route("/segmentDft/{id}", name="deleteFromTrash")
     */
    public function deleteFromTrash($id)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $entityManager = $this->getDoctrine()->getManager();
        $permDelete = $entityManager->getRepository(segments::class)->find($id);

        $entityManager->remove($permDelete);
        $entityManager->flush();

        $this->addFlash(
            'danger',
            'Your segment have permanently deleted.'
        );

        return $this->redirectToRoute('segmentTrash');
    }

    /**
     * @Route("/segmentTrashAll", name="TrashAll")
     */
    public function TrashAll()
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $entityManager = $this->getDoctrine()->getManager();
        $deleteAll = $entityManager->getRepository(segments::class)->findBy(['deleted'=>true]);

        foreach ($deleteAll as $newDelete) {

templates/back/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BackController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'D:/Mes documents/GitHub/The-flow/src/Controller/BackController.php'|file_link(0) }}">src/Controller/BackController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'D:/Mes documents/GitHub/The-flow/templates/back/index.html.twig'|file_link(0) }}">templates/back/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/back/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}The flow | Login{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-3 bo-login-sideL">
            
            <!-- Title -->
            <div class="bo-login-sideL-title">
                <a href="/">
                    <h1>THE FLOW</h1>
                    <p>By Johan SUTTER</p>
                </a>
            </div>
            
            <!-- Hero -->
            <div class="bo-login-sideL-hero">
                <p>Super mega very secret administration part of the site.</p>
            </div>

            <p>But before... please login !</p>
            <p class="text-sm">And yes I realise this wasn't too hard to find.</p>

            <!-- Illustration & credit -->
            <img src="{{ asset('img/myPeeps2.png') }}" alt="Image Cadenas géant avec deux personnes de chaque côté">
            <p class="bo-login-artDisclaimer"> Art created on <a href="https://blush.design/fr" target="_blank">Blush</a></p>

        </div>

        <!-- Forms -->
        <div class="col bo-login-sideR">
            <div class="col-3 bo-login-conatiner">
                <h2>Sign In</h2>
                <form>
                    <div class="form-group">
                        <label>Username</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        <small class="form-text text-muted">It's time to show them who's the boss.</small>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="form-group form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Remember me</label>
                    </div>
                </form>

                <form action="{{ path('segmentView') }}" method="GET">
                        <button type="submit" class="btn btn-primary"><i class="fas fa-unlock-alt"></i>Login</button>
                </form>
            </div>
            
        </div>

    </div>
</div> 

{% endblock %}

templates/back/segmentForm.html.twig
{% extends 'baseBO.html.twig' %}

{% block title %}The flow | Segment Creation{% endblock %}

{% form_theme formSegment 'bootstrap_4_layout.html.twig' %}

{% block body %}

<header>
  <!-- Title -->
  <div class="bo-segView-title">
      <h2>THE SEGMENT CREATION AREA</h2>
      <p>Make something new, make something blue.</p>
      <p class="text-sm">Though it doesn't have to be blue, really !</p>
  </div>

  <!-- Alerts -->
    {% block flash_messages %}
        {% for type, messages in app.session.flashbag.all() %}
            {% for message in messages %}
                <div class="alert alert-{{ type }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    {{ message | raw }}
                </div>
            {% endfor %}
        {% endfor %}
    {% endblock %}

  <!-- Buttons -->
  <form action="{{ path('segmentView') }}" method="GET">
      <button type="submit" class="btn btn-secondary"><i class="fas fa-caret-square-left"></i>Go back</button>
  </form>
</header>

<section>
  <!-- First part title -->
  <div class="bo-segView-title">
      <h3>First part</h3>
      <p>This is the intro of a segment. Make it awesome !</p>
      <p class="text-sm">but keep it short. this is not your life story. </p>
  </div>

  <!-- Forms -->
  <div class="bo-form-firstPart">
    {{ form_start(formSegment) }}
    <div class="form-group">
      <label>Part number</label>
      {{ form_errors(formSegment.part) }}
      {{ form_widget(formSegment.part) }}
    </div>
    <div class="form-group">
      <label>Title</label>
      {{ form_errors(formSegment.title1) }}
      {{ form_widget(formSegment.title1) }}
    </div>
    <div class="form-group">
      <label>Message</label>
      {{ form_errors(formSegment.message1) }}
      {{ form_widget(formSegment.message1, {'attr' : {'rows': "10"}}) }}
    </div>
    <div class="form-group">
      <label>ID of the video</label>
      {{ form_errors(formSegment.link1) }}
      {{ form_widget(formSegment.link1, {'attr' : {'placeholder': "ID of the youtube video"}}) }}
      <small id="emailHelp" class="form-text text-muted">Host the video on Youtube and past the link here.</small>
    </div>
  </div>

  <!-- Second part title -->
  <div class="bo-segView-title">
      <h3>Second part</h3>
      <p>Here we go deeper into details, so come on... open up ! </p>
      <p class="text-sm">This has to be the best place to write about something you like</p>
  </div>

    <div class="form-group">
      <label for="exampleInputEmail1">Title</label>
      {{ form_errors(formSegment.title2) }}
      {{ form_widget(formSegment.title2) }}
    </div>
    <div class="form-group">
      <label>Message</label>
      {{ form_errors(formSegment.message2) }}
      {{ form_widget(formSegment.message2, {'attr' : {'rows': "10"}}) }}
    </div>
    <div>
      <label>Media Upload</label>
    </div>

    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="pills-video-tab" data-toggle="pill" href="#pills-video" role="tab" aria-controls="pills-video" aria-selected="true">Video</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="pills-slider-tab" data-toggle="pill" href="#pills-slider" role="tab" aria-controls="pills-slider" aria-selected="false">Slider</a>
      </li>
      {# <li class="nav-item" role="presentation">
        <a class="nav-link disabled" id="pills-image-tab" data-toggle="pill" href="#pills-image" role="tab" aria-controls="pills-images" aria-selected="false">Image</a>
      </li> #}
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-video" role="tabpanel" aria-labelledby="pills-video-tab">
        <div class="form-group">
          <label>ID of the youtube video</label>
          {{ form_errors(formSegment.link2) }}
          {{ form_widget(formSegment.link2, {'attr' : {'placeholder': "ID of the youtube video"}}) }}
          <small id="emailHelp" class="form-text text-muted">Host the video on Youtube and past the ID here.</small>
        </div>
      </div>
      <div class="tab-pane fade" id="pills-slider" role="tabpanel" aria-labelledby="pills-slider-tab">
        
          <div class="bo-mediaPreview">
            {% if  updates %}
              {% if  updates.linkS1  %}
                <div class="bo-media-grid">
                  <p>Image 01</p>
                  <img src="{{ asset('img/uploads/' ~ updates.linkS1 ) }}">
                  <a href="{{ path('segmentImgTrash1', {'id':updates.id}) }}" class="btn btn-danger"><i class="fas fa-exclamation-triangle"></i>Delete</a>    
                </div>
              {% endif %}

              {% if  updates.linkS2  %}
                <div class="bo-media-grid">
                  <p>Image 02</p>
                  <img src="{{ asset('img/uploads/' ~ updates.linkS2 ) }}">
                  <a href="{{ path('segmentImgTrash2', {'id':updates.id}) }}" class="btn btn-danger"><i class="fas fa-exclamation-triangle"></i>Delete</a>     
                </div>
              {% endif %}

              {% if  updates.linkS3  %}
                <div class="bo-media-grid">
                  <p>Image 03</p>
                  <img src="{{ asset('img/uploads/' ~ updates.linkS3 ) }}">
                  <a href="{{ path('segmentImgTrash3', {'id':updates.id}) }}" class="btn btn-danger"><i class="fas fa-exclamation-triangle"></i>Delete</a>    
                </div>
              {% endif %}
            {% endif %}
          </div>
        
        {% if not updates.linkS1 %}
          <div class="form-group">
            <label for="segment_link_s1">Select image 01</label>
            {{ form_errors(formSegment.link_s1) }}
            {{ form_widget(formSegment.link_s1) }}
          </div>
        {% else %}
            {% do formSegment.link_s1.setRendered() %}
        {% endif %}
        {% if not updates.linkS2 %}
          <div class="form-group">
            <label>Select image 02</label>
            {{ form_errors(formSegment.link_s2) }}
            {{ form_widget(formSegment.link_s2) }}
          </div>
        {% else %}
            {% do formSegment.link_s2.setRendered() %}
        {% endif %}
        {% if not updates.linkS3 %}
          <div class="form-group">
            <label>Select image 03</label>
            {{ form_errors(formSegment.link_s3) }}
            {{ form_widget(formSegment.link_s3) }}
            <small id="uploadlHelp" class="form-text text-muted">Files should not exceed 8Mo.</small>
          </div>
        {% else %}
            {% do formSegment.link_s3.setRendered() %}
        {% endif %}
      </div>
      <div class="tab-pane fade" id="pills-image" role="tabpanel" aria-labelledby="pills-image-tab">
        <div class="form-group">
          <label>Select image</label>
          {{ form_errors(formSegment.link3) }}
          {{ form_widget(formSegment.link3) }}
          <small id="uploadlHelp" class="form-text text-muted">Files should not exceed 8Mo.</small>
        </div>
      </div>
    </div>

    {% if editMode  %}
      <button type="submit" class="btn btn-warning" id="wait-btn"><i id="wait-faw" class="fab fa-firstdraft"></i>Edit</button>
    {% else %}
      <button type="submit" class="btn btn-success" id="wait-btn"><i id="wait-faw" class="fas fa-paper-plane"></i>Publish</button>
    {% endif %}
  {{ form_end(formSegment)}}

{% endblock %}

templates/back/segmentView.html.twig
{% extends 'baseBO.html.twig' %}

{% block title %}The flow | Segment View{% endblock %}

{% block body %}

<header>
    <!-- Title -->
    <div class="bo-segView-title">
        <h2>THE SEGMENT VIEW</h2>
        <p>This is the place where you can see EVERYTHING !</p>
        <p class="text-sm">Except ghost... Definitely not ghost...</p>
    </div>

    <!-- Alerts -->
    {% block flash_messages %}
        {% for type, messages in app.session.flashbag.all() %}
            {% for message in messages %}
                <div class="alert alert-{{ type }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    {{ message | raw }}
                </div>
            {% endfor %}
        {% endfor %}
    {% endblock %}

    {# </div> #}

    <!-- Buttons -->
    <div class="btn-group" role="group" aria-label="Basic example">
        <div class="btn-group mr-2" role="group">
            <form action="{{ path('segmentAdd') }}" method="GET">
                <button type="submit" class="btn btn-primary"><i class="fas fa-edit"></i>Add new</button>
            </form>
        </div>
        {% if trash == true %}
        <div class="btn-group mr-2" role="group">
            <form action="{{ path('segmentTrash') }}" method="GET">
                <button type="submit" class="btn btn-secondary"><i class="fas fa-trash-alt"></i>Trash</button>
            </form>
        </div>
        {% endif %}
    </div>
</header>

<section>

    <!-- Segment list -->
    <div class="bo-segView-group">

        <div class="bo-segView-row-title">
            <div class="row">
                <div class="col-4 col-sm-2 col-lg-4">
                <label>Titles</label>
                </div>
                <div class="col-4 col-sm-2 col-lg-4">
                <label>Last update</label>
                </div>
                <div class="col col-sm-2 col-lg-4">
                <label>Options</label>
                </div>
            </div>
        </div>

        {% for segment in segments %}
            <div class="bo-segView-row">
                <div class="row">
                    <div class="col col-sm-2 col-lg-4 bo-segView-row-text">
                        <h3>{{ segment.title1 }}</h3>
                    </div>
                    <div class="col col-sm-2 col-lg-4 bo-segView-row-text bo-segView-row-date">
                        <p>{{ segment.createdAt| date('d/m/Y') }} at {{ segment.createdAt| date('H:i') }}</p>
                    </div>
                    <div class="col-4 col-sm-2 col-lg-4">
                        <div class="bo-segView-btnGroup">
                            <form action="{{ path('segmentEdit', {'id':segment.id}) }}" method="GET">
                                <button type="submit" class="btn btn-warning"><i class="fab fa-firstdraft"></i>Edit</button>
                            </form>

                            <button type="button" class="btn btn-danger "data-toggle="modal" data-target="#staticBackdrop{{ segment.id }}"><i class="fas fa-trash-alt"></i>Delete</button>

                            <!-- Modal -->
                            <div class="modal fade" id="staticBackdrop{{ segment.id }}" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel{{ segment.id }}" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="staticBackdropLabel{{ segment.id }}">Delete segement</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            You do realise that you will put in the trash all the work and effort you have put in this segment ?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                                            <form action="{{ path('segmentBin', {'id':segment.id}) }}" method="GET">
                                                <button type="submit" class="btn btn-danger"><i class="fas fa-exclamation-triangle"></i>Delete</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
<section>

{% endblock %}